version: 2

sources:
  - name: landing_zone
    description: "Raw incident management data"
    schema: landing_zone
    tables:

      - name: slack_messages
        description: "Slack messages data from incident management channels"
        columns:
          - name: hasfile
            description: "Whether the message has a file attachment"
          - name: hasfiles
            description: "Whether the message has multiple file attachments"
          - name: type
            description: "Type of Slack message"
          - name: subtype
            description: "Subtype of Slack message"
          - name: team
            description: "Slack team identifier"
          - name: channel
            description: "Slack channel identifier"
          - name: user
            description: "User identifier who sent the message"
          - name: username
            description: "Username of the message sender"
          - name: text
            description: "Message content text"
          - name: ts
            description: "Message timestamp"
            tests:
              - not_null
          - name: threadts
            description: "Thread timestamp if message is part of a thread"
          - name: intro
            description: "Whether this is an intro message"
          - name: starred
            description: "Whether the message is starred"
          - name: wibblr
            description: "Wibblr flag"
          - name: appid
            description: "Application identifier"
          - name: botid
            description: "Bot identifier if message is from a bot"
          - name: botlink
            description: "Bot link if message is from a bot"
          - name: displayasbot
            description: "Whether to display the message as from a bot"
          - name: upload
            description: "Whether the message contains an upload"
          - name: parentuserid
            description: "Parent user identifier"
          - name: clientmsgid
            description: "Client message identifier"
          - name: unfurllinks
            description: "Whether to unfurl links in the message"
          - name: unfurlmedia
            description: "Whether to unfurl media in the message"
          - name: threadbroadcast
            description: "Whether the thread message is broadcast to the channel"
          - name: locked
            description: "Whether the message is locked"
          - name: subscribed
            description: "Whether the user is subscribed to the thread"
          - name: hidden
            description: "Whether the message is hidden"
          - name: nonotifications
            description: "Whether notifications are disabled"
          - name: chunkindex
            description: "Index of the data chunk"
          - name: chunkcount
            description: "Total number of data chunks"
          - name: ingestts
            description: "Timestamp when the data was ingested"
          - name: workspaceid
            description: "Slack workspace identifier"

      - name: slack_members
        description: "Slack channel membership data"
        columns:
          - name: conversationid
            description: "Unique identifier for the Slack conversation/channel"
            tests:
              - not_null
          - name: conversationtype
            description: "Type of conversation (channel, group, DM, etc.)"
          - name: memberids
            description: "Array of member user IDs in the conversation"
          - name: memberemails
            description: "Array of member email addresses in the conversation"
          - name: isprivate
            description: "Whether the conversation is private"
          - name: lastupdated
            description: "Timestamp when the membership data was last updated"
            tests:
              - not_null

      - name: stream_slack_messages
        description: "Streaming Slack messages data for real-time incident management"
        columns:
          - name: hasfile
            description: "Whether the message has a file attachment"
          - name: hasfiles
            description: "Whether the message has multiple file attachments"
          - name: type
            description: "Type of Slack message"
          - name: subtype
            description: "Subtype of Slack message"
          - name: team
            description: "Slack team identifier"
          - name: channel
            description: "Slack channel identifier"
            tests:
              - not_null
          - name: user
            description: "User identifier who sent the message"
          - name: username
            description: "Username of the message sender"
          - name: text
            description: "Message content text"
          - name: ts
            description: "Message timestamp"
            tests:
              - not_null
          - name: threadts
            description: "Thread timestamp if message is part of a thread"
          - name: intro
            description: "Whether this is an intro message"
          - name: starred
            description: "Whether the message is starred"
          - name: wibblr
            description: "Wibblr flag"
          - name: appid
            description: "Application identifier"
          - name: botid
            description: "Bot identifier if message is from a bot"
          - name: botlink
            description: "Bot link if message is from a bot"
          - name: displayasbot
            description: "Whether to display the message as from a bot"
          - name: upload
            description: "Whether the message contains an upload"
          - name: parentuserid
            description: "Parent user identifier"
          - name: clientmsgid
            description: "Client message identifier"
          - name: unfurllinks
            description: "Whether to unfurl links in the message"
          - name: unfurlmedia
            description: "Whether to unfurl media in the message"
          - name: threadbroadcast
            description: "Whether the thread message is broadcast to the channel"
          - name: locked
            description: "Whether the message is locked"
          - name: subscribed
            description: "Whether the user is subscribed to the thread"
          - name: hidden
            description: "Whether the message is hidden"
          - name: nonotifications
            description: "Whether notifications are disabled"
          - name: chunkindex
            description: "Index of the data chunk"
          - name: chunkcount
            description: "Total number of data chunks"
          - name: ingestts
            description: "Timestamp when the data was ingested"
            tests:
              - not_null
          - name: workspaceid
            description: "Slack workspace identifier"

      - name: file_hashes
        description: "File hash values for data integrity and deduplication"
        columns:
          - name: hash_value
            description: "Computed hash value of the file"
            tests:
              - not_null
          - name: source_system
            description: "System or application that generated the file"
          - name: doc_id
            description: "Document identifier associated with the file"
          - name: event_ts
            description: "Timestamp when the hash event occurred"
          - name: algorithm
            description: "Hashing algorithm used (e.g., MD5, SHA-256)"

      - name: doc_metadata
        description: "Document metadata for files shared in incident management channels"
        columns:
          - name: event_ts
            description: "Timestamp when the document event occurred"
            tests:
              - not_null
          - name: channel_id
            description: "Slack channel identifier where the document was shared"
            tests:
              - not_null
          - name: user_id
            description: "User identifier who shared the document"
          - name: file_id
            description: "Unique file identifier"
            tests:
              - not_null
          - name: file_name
            description: "Name of the file"
          - name: file_mimetype
            description: "MIME type of the file (e.g., application/pdf, image/png)"
          - name: file_size
            description: "Size of the file in bytes"
          - name: content_sha256
            description: "SHA-256 hash of the file content for integrity verification"
          - name: staged_file_path
            description: "Path where the file is staged for processing"

      # Users
      - name: users
        description: "System users including employees, customers, and system accounts"
        columns:
          - name: id
            description: "Unique user identifier"
            tests:
              - unique
              - not_null
          - name: email
            description: "User email address"
            tests:
              - unique
              - not_null
          - name: role
            description: "User role in the system"
          - name: is_active
            description: "Whether the user account is active"

      # Incidents
      - name: incidents
        description: "Main incidents table containing all incident records"
        columns:
          - name: incident_number
            description: "Human-readable incident number and primary key"
            tests:
              - unique
              - not_null
          - name: title
            description: "Brief incident title"
            tests:
              - not_null
          - name: category
            description: "Incident category classification"
          - name: priority
            description: "Incident priority level"
            tests:
              - accepted_values:
                  values: ['low', 'medium', 'high', 'critical']
          - name: status
            description: "Current incident status"
            tests:
              - accepted_values:
                  values: ['open', 'in_progress', 'pending_customer', 'pending_vendor', 'resolved', 'closed', 'cancelled']
          - name: assignee_id
            description: "ID of user assigned to the incident"
            tests:
              - relationships:
                  to: source('landing_zone', 'users')
                  field: id
          - name: reportee_id
            description: "ID of user who reported the incident"
            tests:
              - relationships:
                  to: source('landing_zone', 'users')
                  field: id
          - name: created_at
            description: "Timestamp when the incident was created"
            tests:
              - not_null
          - name: closed_at
            description: "Timestamp when the incident was closed"
          - name: updated_at
            description: "Timestamp when the incident was last updated"
            tests:
              - not_null
          - name: source_system
            description: "Where the incident originated (e.g., 'monitoring', 'customer_portal', 'manual')"
          - name: external_source_id
            description: "Reference to external source systems"
          - name: has_attachments
            description: "Indicates if incident has any attachments"
          - name: slack_message_id
            description: "Reference to the original Slack message that created this incident"

      # Incident Comment History
      - name: incident_comment_history
        description: "Simplified comments table for incident communication"
        columns:
          - name: id
            description: "Unique comment identifier"
            tests:
              - unique
              - not_null
          - name: incident_number
            description: "Reference to the incident"
            tests:
              - not_null
              - relationships:
                  to: source('landing_zone', 'incidents')
                  field: incident_number
          - name: author_id
            description: "ID of comment author"
            tests:
              - not_null
              - relationships:
                  to: source('landing_zone', 'users')
                  field: id
          - name: content
            description: "Comment content text"
            tests:
              - not_null
          - name: created_at
            description: "Timestamp when the comment was created"
            tests:
              - not_null

models:
  - name: closed_incidents
    description: "Closed incidents with basic metrics and analysis"
    columns:
      - name: incident_number
        description: "Human-readable incident number and primary key"
        tests:
          - unique
          - not_null
      - name: title
        description: "Brief incident title"
        tests:
          - not_null
      - name: category
        description: "Incident category classification"
      - name: priority
        description: "Incident priority level"
        tests:
          - accepted_values:
              values: ['low', 'medium', 'high', 'critical']
      - name: status
        description: "Current incident status (closed or resolved)"
        tests:
          - accepted_values:
              values: ['closed', 'resolved']
      - name: assignee_id
        description: "ID of user assigned to the incident"
      - name: reportee_id
        description: "ID of user who reported the incident"
      - name: created_at
        description: "Timestamp when the incident was created"
        tests:
          - not_null
      - name: closed_at
        description: "Timestamp when the incident was closed"
        tests:
          - not_null
      - name: updated_at
        description: "Timestamp when the incident was last updated"
      - name: source_system
        description: "Where the incident originated"
      - name: external_source_id
        description: "Reference to external source systems"
      - name: has_attachments
        description: "Indicates if incident has any attachments"
      - name: total_resolution_hours
        description: "Total time from creation to closure in hours"
        tests:
          - not_null
      - name: closed_month
        description: "Month when the incident was closed (for trending)"
      - name: closed_year
        description: "Year when the incident was closed (for trending)"
      - name: closed_quarter
        description: "Quarter when the incident was closed (for trending)"

