incident_management:
  outputs:
    dev:
      type: snowflake
      account: ""
      database: "incident_management"
      role: "dbt_projects_engineer"
      schema: "bronze_zone"
      user: ""
      warehouse: "incident_management_dbt_wh"
  target: "dev"


