incident_management:
  outputs:
    dev:
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}"
      database: "{{ env_var('DBT_MODEL_DATABASE') }}"
      role: "{{ env_var('DBT_MODEL_ROLE') }}"
      schema: "{{ env_var('DBT_MODEL_SCHEMA') }}"
      threads: "{{ env_var('DBT_THREADS', 1) | as_number }}"
      type: snowflake
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
      warehouse: "{{ env_var('DBT_SNOWFLAKE_WAREHOUSE') }}"
    prod:
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}"
      database: "{{ env_var('DBT_MODEL_DATABASE') }}"
      role: "{{ env_var('DBT_MODEL_ROLE') }}"
      schema: "{{ env_var('DBT_MODEL_SCHEMA') }}"
      threads: "{{ env_var('DBT_THREADS', 2) | as_number }}"
      type: snowflake
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
      warehouse: "{{ env_var('DBT_SNOWFLAKE_WAREHOUSE') }}"
  target: "{{ env_var('DBT_TARGET', 'dev') }}"

