incident_management:
  outputs:
    dev:
      type: snowflake
      account: ""
      database: "v1_incident_management"
      role: "v1_dbt_projects_engineer"
      schema: "bronze_zone"
      user: ""
      warehouse: "v1_demo_wh"
  target: "dev"


